### PR TITLE
Supporting UserContext in bug reports of Android and iOS native errors

### PR DESCRIPTION
**Pull request by fzyzcjy**
see #14 and #50

### CODE REVIEW

**Comment by fzyzcjy** [comment]
(a bugfix commit will be soon commited)

I do see native crash reports userid now, for both android and ios:

image
image

Also, when I set the user to null, it correctly give no user context:

image
image

**Comment by dotdoom** [comment]
Thanks for the pull request!  Looks like the build on macOS isn't happy.

The implementation looks good, however, I am concerned that we further diverge from a seamless API into setNativeXxx methods.  I think API users would rather not have to remember an extra call to set the same property on native platform, and instead have it populated automatically.  WDYT?

**Comment by fzyzcjy** [comment]
@dotdoom I completely agree. I wrote like that just because I saw the "setNativeEnvironment" so I thought you like that style of setting the native data.

**Comment by fzyzcjy** [comment]
About the fail of macos, seems to be caused by me updating sentry 5.x -> 6.x. However, you know, we should update the version to get latest features. Especially considering that, this flutter_sentry repo is a wrapper of the sentry package.

image

**Comment by dotdoom** [comment]
Updated Sentry to 6.
Done in #51

**Pull request closed without merging**
