### PR TITLE
Support Release Health on iOS

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by kuhnroyal** [comment]
Just saw this PR when I wanted to create a PR myself.

I think it would be cleaner to have only one `SentrySDK.start` call using a dictionary `var options = [String: Any]()` to fill all the options.

These are my changes for the README Release health tracking section:
```markdown

   **NOTE**: Session tracking is disabled by default and the timeout for a session defaults to 30000 milliseconds (30 seconds).

   - iOS: in `ios/Runner/Info.plist`:

     ```xml
     <dict>
       ... existing configuration parameters ...
       <key>SentryEnableAutoSessionTracking</key>
       <true/>
       <key>SentrySessionTrackingIntervalMillis</key>
       <integer>10000</integer>
     </dict>
     ```

   - Android: in `android/app/src/main/AndroidManifest.xml`:

     ```xml
     <application>
       <meta-data
           android:name="io.sentry.session-tracking.enable"
           android:value="true"/>
       <meta-data
           android:name="io.sentry.session-tracking.timeout-interval-millis"
           android:value="10000" />
     ```
```

**Comment by dotdoom** [comment]
@kuhnroyal cool, I didn't know it's possible to pass options as a map.  That would indeed be cleaner.  I'm not fluent in Swift (and apparently neither in Kotlin -- #38).  Would you like to take over this PR then?

**Comment by kuhnroyal** [comment]
I am rebasing my stuff on this and making a new PR.

**Comment by kuhnroyal** [comment]
Added #40 based on this.

**Pull request closed without merging**
